'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '@/lib/client-api';

const tabs = [
  ['overview','Огляд'],['courses','Курси'],['spaces','Простори'],['media','Медіатека'],['providers','Провайдери'],['imports','Імпорт'],['users','Користувачі'],['analytics','Аналітика'],['shares','Шеринг'],['payments','Платежі'],['settings','Налаштування'],['admins','Адміни']
];

function Card({children,className=''}){return <div className={`adminCard ${className}`}>{children}</div>}
function Field({label,children}){return <label className="adminField"><span>{label}</span>{children}</label>}

export default function AdminPage(){
  const [tab,setTab]=useState('overview'); const [data,setData]=useState(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [providers,setProviders]=useState([]);
  async function load(which=tab){setError('');try{if(which==='imports'){setData({ok:true});return;}const path=which==='overview'?'dashboard':which;const r=await apiFetch(`/api/admin/${path}`);setData(r);if(which==='providers')setProviders(r.providers||[]);}catch(e){setError(e.message)}}
  useEffect(()=>{load(tab)},[tab]);
  async function post(path,body,form=false){setBusy(true);setError('');try{const r=await apiFetch(path,{method:'POST',body:form?body:JSON.stringify(body),...(form?{headers:{}}:{})});await load(tab);return r;}catch(e){setError(e.message);throw e}finally{setBusy(false)}}

  return <main className="adminShell">
    <header className="adminHeader"><div><span className="eyebrow">OWNER CMS</span><h1>Керування платформою</h1></div><Link className="secondary linkButton" href="/">← Mini App</Link></header>
    <nav className="adminTabs">{tabs.map(([k,l])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}>{l}</button>)}</nav>
    {error&&<div className="inlineError">{error}</div>}
    {!data&&!error&&<div className="loader"/>}
    {data&&tab==='overview'&&<Overview data={data}/>} 
    {data&&tab==='courses'&&<Courses data={data} post={post} busy={busy}/>} 
    {data&&tab==='spaces'&&<Spaces data={data} post={post} busy={busy}/>} 
    {data&&tab==='media'&&<Media data={data} post={post} busy={busy} providers={providers} loadProviders={async()=>{try{const r=await apiFetch('/api/admin/providers');setProviders(r.providers||[])}catch{}}}/>} 
    {data&&tab==='providers'&&<Providers data={data} post={post} busy={busy}/>} 
    {data&&tab==='imports'&&<Imports post={post} busy={busy}/>} 
    {data&&tab==='users'&&<Users data={data}/>} 
    {data&&tab==='analytics'&&<Analytics data={data}/>} 
    {data&&tab==='shares'&&<Shares data={data}/>} 
    {data&&tab==='payments'&&<Payments data={data}/>} 
    {data&&tab==='settings'&&<Settings data={data} busy={busy} onSave={async(payload)=>{setBusy(true);try{await apiFetch('/api/admin/settings',{method:'PUT',body:JSON.stringify(payload)});await load('settings')}finally{setBusy(false)}}}/>} 
    {data&&tab==='admins'&&<Admins data={data} post={post} busy={busy}/>} 
  </main>
}

function Overview({data}){const s=data.stats||{};return <><div className="statGrid">{[['Користувачі',s.users],['Курси',s.courses],['Простори',s.spaces],['Активні проходження',s.active_attempts],['Завершені',s.finished_attempts],['Активні підписки',s.active_subscriptions],['Отримано Stars',`${s.stars_total||0} ⭐`]].map(([l,v])=><Card key={l}><span>{l}</span><strong>{v??0}</strong></Card>)}</div><Card><h2>Архітектура v2</h2><p>Курси → локалізації → кроки → блоки → медіа. Простори визначають, які курси бачить конкретний Telegram-канал. Контент можна змінювати без GitHub/Vercel.</p></Card></>}

function Courses({data,post,busy}){const[c,setC]=useState({title:'',slug:'',locale:'uk',is_free:true,one_time_price_stars:99});return <><div className="adminGrid two"><Card><h2>Курси</h2><div className="adminList">{(data.courses||[]).map(x=><Link key={x.slug} href={`/admin/course/${x.slug}`} className="adminListItem"><div><strong>{x.short_title}</strong><small>{x.slug} · {x.total_steps} кроків · {x.is_published?'опубліковано':'чернетка'}</small></div><span>Редагувати →</span></Link>)}</div></Card><Card><h2>Новий курс</h2><Field label="Назва"><input value={c.title} onChange={e=>setC({...c,title:e.target.value})}/></Field><Field label="Slug (латиницею)"><input value={c.slug} onChange={e=>setC({...c,slug:e.target.value})}/></Field><Field label="Мова"><select value={c.locale} onChange={e=>setC({...c,locale:e.target.value})}><option value="uk">Українська</option><option value="ru">Русский</option></select></Field><label className="check"><input type="checkbox" checked={c.is_free} onChange={e=>setC({...c,is_free:e.target.checked})}/> Безкоштовний</label>{!c.is_free&&<Field label="Ціна, ⭐"><input type="number" value={c.one_time_price_stars} onChange={e=>setC({...c,one_time_price_stars:Number(e.target.value)})}/></Field>}<button className="primary" disabled={busy||!c.title} onClick={()=>post('/api/admin/courses',c)}>Створити чернетку</button></Card></div></>}

function Spaces({data,post,busy}){const[s,setS]=useState({title:'',slug:'',default_locale:'uk'});return <div className="adminGrid two"><Card><h2>Простори / вітрини</h2>{(data.spaces||[]).map(x=><Link key={x.slug} className="adminListItem" href={`/admin/space/${x.slug}`}><div><strong>{x.short_title}</strong><small>{x.slug} · {x.space_courses?.length||0} курсів</small></div><span>Редагувати →</span></Link>)}</Card><Card><h2>Новий простір</h2><Field label="Назва"><input value={s.title} onChange={e=>setS({...s,title:e.target.value})}/></Field><Field label="Slug"><input value={s.slug} onChange={e=>setS({...s,slug:e.target.value})}/></Field><button className="primary" disabled={busy||!s.title} onClick={()=>post('/api/admin/spaces',s)}>Створити</button><p className="hint">Після створення адмінка покаже direct link із startapp для конкретного каналу.</p></Card></div>}

function Media({data,post,busy,providers,loadProviders}){const[m,setM]=useState({title:'',provider_key:'youtube',media_type:'video',source_locator:'',protection_level:'enhanced',watermark_enabled:true});useEffect(()=>{if(!providers.length)loadProviders()},[]);const[file,setFile]=useState(null);return <><div className="adminGrid two"><Card><h2>Медіатека</h2><div className="adminList compactList">{(data.media||[]).map(x=><div className="adminListItem" key={x.id}><div><strong>{x.title}</strong><small>{x.media_type} · {x.provider_key} · {x.protection_level}</small></div><code>{x.id.slice(0,8)}</code></div>)}</div></Card><div><Card><h2>Додати з URL / ID</h2><Field label="Назва"><input value={m.title} onChange={e=>setM({...m,title:e.target.value})}/></Field><Field label="Провайдер"><select value={m.provider_key} onChange={e=>setM({...m,provider_key:e.target.value})}>{providers.map(p=><option key={p.provider_key} value={p.provider_key}>{p.display_name}</option>)}</select></Field><Field label="Тип"><select value={m.media_type} onChange={e=>setM({...m,media_type:e.target.value})}>{['video','audio','pdf','image','file'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="URL / video ID / path"><textarea value={m.source_locator} onChange={e=>setM({...m,source_locator:e.target.value})}/></Field><Field label="Захист"><select value={m.protection_level} onChange={e=>setM({...m,protection_level:e.target.value})}><option>standard</option><option>enhanced</option><option>maximum</option></select></Field><label className="check"><input type="checkbox" checked={m.watermark_enabled} onChange={e=>setM({...m,watermark_enabled:e.target.checked})}/> Персональний watermark</label><button className="primary" disabled={busy||!m.source_locator} onClick={()=>post('/api/admin/media',m)}>Додати</button></Card><Card><h2>Завантажити у приватний Storage</h2><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><p className="hint">Для великих відео використовуйте Cloudflare/Bunny/S3 та додавайте їх як зовнішній media asset.</p><button className="secondary" disabled={busy||!file} onClick={async()=>{const fd=new FormData();fd.append('file',file);fd.append('title',file.name);fd.append('media_type',m.media_type);fd.append('protection_level',m.protection_level);await post('/api/admin/media/upload',fd,true)}}>Завантажити</button></Card></div></div></>}

function Providers({data,post,busy}){const[p,setP]=useState({provider_key:'',display_name:'',provider_type:'generic',delivery_type:'direct',secret_env_prefix:'',config:'{}'});return <div className="adminGrid two"><Card><h2>Медіапровайдери</h2>{(data.providers||[]).map(x=><div className="adminListItem" key={x.provider_key}><div><strong>{x.display_name}</strong><small>{x.provider_key} · {x.delivery_type} · {x.is_enabled?'ON':'OFF'}</small></div><code>{x.secret_env_prefix||'без secret'}</code></div>)}</Card><Card><h2>Додати провайдера</h2><Field label="Ключ"><input value={p.provider_key} onChange={e=>setP({...p,provider_key:e.target.value})}/></Field><Field label="Назва"><input value={p.display_name} onChange={e=>setP({...p,display_name:e.target.value})}/></Field><Field label="Delivery"><select value={p.delivery_type} onChange={e=>setP({...p,delivery_type:e.target.value})}>{['supabase','youtube','vimeo','cloudflare_stream','bunny_stream','s3','direct','iframe','hls','dash'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Secret env prefix"><input value={p.secret_env_prefix} onChange={e=>setP({...p,secret_env_prefix:e.target.value})} placeholder="MEDIA_S3_ARCHIVE"/></Field><Field label="Config JSON"><textarea value={p.config} onChange={e=>setP({...p,config:e.target.value})}/></Field><button className="primary" disabled={busy||!p.provider_key} onClick={()=>post('/api/admin/providers',{...p,config:JSON.parse(p.config||'{}')})}>Додати</button></Card></div>}

function Imports({post,busy}){const[file,setFile]=useState(null);const[result,setResult]=useState(null);return <Card><h2>Імпорт готового курсу</h2><p>Завантажте один <code>.zip</code> у форматі Course Package. Текст, локалізації, кроки, блоки й медіапосилання імпортуються як <b>чернетка</b>. Великі відео краще передавати посиланнями/ID провайдерів.</p><input type="file" accept=".zip" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary" disabled={busy||!file} onClick={async()=>{const fd=new FormData();fd.append('file',file);const r=await post('/api/admin/import',fd,true);setResult(r)}}>Імпортувати пакет</button>{result&&<pre className="report">{JSON.stringify(result.report,null,2)}</pre>}<p className="hint">Шаблон і документація лежать у <code>course-package/</code> в архіві проєкту.</p></Card>}

function Users({data}){return <Card><h2>Користувачі</h2><div className="tableWrap"><table><thead><tr><th>Користувач</th><th>ID</th><th>Мова</th><th>Проходження</th></tr></thead><tbody>{(data.users||[]).map(u=><tr key={u.telegram_id}><td><Link href={`/admin/user/${u.telegram_id}`}>{u.first_name} {u.username&&<small>@{u.username}</small>}</Link></td><td>{u.telegram_id}</td><td>{u.language_code||'—'}</td><td>{(u.course_attempts||[]).map(a=><div key={a.id}>{a.course_slug}: {a.completed_steps} ({a.status})</div>)}</td></tr>)}</tbody></table></div></Card>}
function Payments({data}){return <Card><h2>Telegram Stars</h2><div className="tableWrap"><table><thead><tr><th>Дата</th><th>Користувач</th><th>Тип</th><th>Курс</th><th>Stars</th><th>Статус</th></tr></thead><tbody>{(data.payments||[]).map(p=><tr key={p.telegram_payment_charge_id}><td>{new Date(p.paid_at).toLocaleString('uk-UA')}</td><td>{p.users?.username?'@'+p.users.username:p.users?.first_name||p.telegram_id}</td><td>{p.kind}</td><td>{p.course_slug||'—'}</td><td>{p.amount_stars} ⭐</td><td>{p.status}</td></tr>)}</tbody></table></div></Card>}

function Settings({data,onSave,busy}){const map=useMemo(()=>Object.fromEntries((data.settings||[]).map(s=>[s.key,s.value])),[data]);const[support,setSupport]=useState(map.support||{enabled:false,type:'telegram_bot',value:''});const[donations,setDonations]=useState((map.donation_options||[10,25,50,100]).join(','));const[plans,setPlans]=useState(data.plans||[]);return <div className="adminGrid two"><Card><h2>Підтримка</h2><label className="check"><input type="checkbox" checked={support.enabled} onChange={e=>setSupport({...support,enabled:e.target.checked})}/> Показувати контакт підтримки</label><Field label="Тип"><select value={support.type} onChange={e=>setSupport({...support,type:e.target.value})}><option value="telegram_bot">Telegram bot</option><option value="telegram_username">Telegram username</option><option value="url">URL</option><option value="email">Email</option></select></Field><Field label="Контакт"><input value={support.value||''} onChange={e=>setSupport({...support,value:e.target.value})} placeholder="@SupportBot"/></Field><Field label="Донати ⭐ через кому"><input value={donations} onChange={e=>setDonations(e.target.value)}/></Field><button className="primary" disabled={busy} onClick={()=>onSave({settings:[{key:'support',value:support},{key:'donation_options',value:donations.split(',').map(v=>Number(v.trim())).filter(Boolean)}]})}>Зберегти</button></Card><Card><h2>Підписки</h2>{plans.map((p,i)=><div className="planEdit" key={p.plan_key}><strong>{p.plan_key}</strong><Field label="Назва"><input value={p.title} onChange={e=>setPlans(plans.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/></Field><Field label="Ціна ⭐"><input type="number" value={p.price_stars} onChange={e=>setPlans(plans.map((x,j)=>j===i?{...x,price_stars:Number(e.target.value)}:x))}/></Field></div>)}<button className="primary" disabled={busy} onClick={()=>onSave({plans})}>Зберегти тарифи</button></Card></div>}

function Admins({data,post,busy}){const[a,setA]=useState({telegram_id:'',role:'editor',label:''});return <div className="adminGrid two"><Card><h2>Адміністратори</h2>{(data.admins||[]).map(x=><div className="adminListItem" key={x.telegram_id}><div><strong>{x.label||x.telegram_id}</strong><small>{x.telegram_id}</small></div><span>{x.role}</span></div>)}</Card><Card><h2>Додати / змінити</h2><Field label="Telegram numeric ID"><input value={a.telegram_id} onChange={e=>setA({...a,telegram_id:e.target.value})}/></Field><Field label="Роль"><select value={a.role} onChange={e=>setA({...a,role:e.target.value})}>{['owner','admin','editor','support','analyst'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Підпис"><input value={a.label} onChange={e=>setA({...a,label:e.target.value})}/></Field><button className="primary" disabled={busy||!a.telegram_id} onClick={()=>post('/api/admin/admins',a)}>Зберегти</button></Card></div>}

function Analytics({data}){return <div className="adminGrid">{(data.courses||[]).map(c=><Card key={c.course_slug}><div className="sectionHead"><div><h2>{c.title}</h2><p>{c.started} стартів · {c.finished} завершень · {c.completion_rate}%</p></div></div><div className="analyticsSteps">{c.steps.filter((_,i)=>i<30||i===c.steps.length-1).map(s=><div key={s.step}><span>{s.step}</span><div className="miniBar"><i style={{width:`${c.started?Math.min(100,s.completed/c.started*100):0}%`}}/></div><small>{s.completed}</small></div>)}</div>{c.steps.length>31&&<p className="hint">Показано перші 30 кроків + фінальний. Дані всіх кроків доступні через API.</p>}</Card>)}</div>}
function Shares({data}){return <Card><h2>Шеринг / сарафанне радіо</h2><div className="tableWrap"><table><thead><tr><th>Дата</th><th>Хто поділився</th><th>Space</th><th>Курс/крок</th><th>Відкриття</th></tr></thead><tbody>{(data.shares||[]).map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('uk-UA')}</td><td>{x.users?.username?'@'+x.users.username:x.users?.first_name||x.telegram_id}</td><td>{x.space_slug}</td><td>{x.course_slug}{x.step_number?` / ${x.step_number}`:''}</td><td>{x.opened_count}</td></tr>)}</tbody></table></div></Card>}
