'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { apiFetch } from '@/lib/client-api';

function Field({label,children}){return <label className="adminField"><span>{label}</span>{children}</label>}
export default function CourseAdmin(){
  const{slug}=useParams();const[data,setData]=useState(null);const[allSpaces,setAllSpaces]=useState([]);const[form,setForm]=useState(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
  async function load(){try{setError('');const[r,s]=await Promise.all([apiFetch(`/api/admin/courses/${slug}`),apiFetch('/api/admin/spaces')]);setData(r);setAllSpaces(s.spaces||[]);const locs=[...(r.locales||[])];if(!locs.find(x=>x.locale==='uk'))locs.push({locale:'uk',title:r.course.title,short_title:r.course.short_title,intro_text:r.course.intro_text,description:r.course.description||'',is_published:true});if(!locs.find(x=>x.locale==='ru'))locs.push({locale:'ru',title:'',short_title:'',intro_text:'',description:'',is_published:false});setForm({...r.course,locales:locs});}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[slug]);
  const assignments=useMemo(()=>{if(!data)return[];return allSpaces.map(sp=>{const old=(data.spaces||[]).find(x=>x.space_slug===sp.slug);return{space_slug:sp.slug,title:sp.short_title,is_visible:old?.is_visible??false,sort_order:old?.sort_order||100,price_override_stars:old?.price_override_stars||'',access_override:old?.access_override||''}})},[allSpaces,data]);
  const[assign,setAssign]=useState([]);useEffect(()=>setAssign(assignments),[JSON.stringify(assignments)]);
  async function save(){setBusy(true);try{await apiFetch(`/api/admin/courses/${slug}`,{method:'PUT',body:JSON.stringify({...form,unlock_hour:Number(form.unlock_hour),restart_offer_after_missed_days:Number(form.restart_offer_after_missed_days),one_time_price_stars:form.is_free?null:Number(form.one_time_price_stars||99),available_locales:form.locales.filter(x=>x.title&&x.is_published!==false).map(x=>x.locale),space_assignments:assign})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function addStep(){setBusy(true);try{const r=await apiFetch(`/api/admin/courses/${slug}/steps`,{method:'POST',body:JSON.stringify({locale:form.default_locale||'uk'})});location.href=`/admin/course/${slug}/step/${r.step_number}`}catch(e){setError(e.message);setBusy(false)}}
  async function uploadBrand(file,kind,field){if(!file)return;setBusy(true);setError('');try{const fd=new FormData();fd.append('file',file);fd.append('kind',kind);const r=await apiFetch('/api/admin/public-assets/upload',{method:'POST',body:fd});setForm(prev=>({...prev,[field]:r.url}))}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(!form)return <main className="adminShell"><Link href="/admin">← Адмінка</Link>{error?<div className="inlineError">{error}</div>:<div className="loader"/>}</main>;
  return <main className="adminShell"><header className="adminHeader"><div><Link href="/admin">← Адмінка</Link><h1>{form.short_title}</h1><code>{slug}</code></div><div className="adminActions"><button className="secondary" onClick={addStep}>+ Крок</button><button className="primary" disabled={busy} onClick={save}>{busy?'Збереження…':'Зберегти все'}</button></div></header>{error&&<div className="inlineError">{error}</div>}
    <div className="adminGrid two">
      <div>
        <div className="adminCard"><h2>Налаштування курсу</h2><div className="formGrid"><Field label="Внутрішня назва"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Коротка назва"><input value={form.short_title} onChange={e=>setForm({...form,short_title:e.target.value})}/></Field><Field label="Година відкриття"><input type="number" min="0" max="23" value={form.unlock_hour} onChange={e=>setForm({...form,unlock_hour:e.target.value})}/></Field><Field label="Пауза до пропозиції перезапуску, днів"><input type="number" value={form.restart_offer_after_missed_days} onChange={e=>setForm({...form,restart_offer_after_missed_days:e.target.value})}/></Field><Field label="Логотип / URL"><input value={form.logo_path||''} onChange={e=>setForm({...form,logo_path:e.target.value})}/><input type="file" accept="image/*" onChange={e=>uploadBrand(e.target.files?.[0],'course-logo','logo_path')}/></Field><Field label="Обкладинка / URL"><input value={form.cover_path||''} onChange={e=>setForm({...form,cover_path:e.target.value})}/><input type="file" accept="image/*" onChange={e=>uploadBrand(e.target.files?.[0],'course-cover','cover_path')}/></Field><Field label="Максимум кроків за день"><input type="number" min="1" value={form.max_steps_per_day||1} onChange={e=>setForm({...form,max_steps_per_day:Number(e.target.value)||1})}/></Field><label className="check"><input type="checkbox" checked={!!form.allow_previous_steps} onChange={e=>setForm({...form,allow_previous_steps:e.target.checked})}/> Дозволяти перегляд попередніх кроків (готовність правила для майбутніх курсів)</label><Field label="Захист"><select value={form.protection_level||'standard'} onChange={e=>setForm({...form,protection_level:e.target.value})}><option>standard</option><option>enhanced</option><option>maximum</option></select></Field><Field label="Сортування"><input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></Field></div><label className="check"><input type="checkbox" checked={form.first_step_immediate!==false} onChange={e=>setForm({...form,first_step_immediate:e.target.checked})}/> Крок 1 одразу після старту</label><label className="check"><input type="checkbox" checked={!!form.is_free} onChange={e=>setForm({...form,is_free:e.target.checked})}/> Безкоштовний</label>{!form.is_free&&<Field label="Ціна назавжди, ⭐"><input type="number" value={form.one_time_price_stars||99} onChange={e=>setForm({...form,one_time_price_stars:Number(e.target.value)})}/></Field>}<label className="check"><input type="checkbox" checked={form.included_in_subscription!==false} onChange={e=>setForm({...form,included_in_subscription:e.target.checked})}/> Входить у All Access</label><label className="check"><input type="checkbox" checked={!!form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/> Курс опублікований</label></div>
        <div className="adminCard"><h2>Локалізації</h2>{form.locales.map((l,i)=><div className="localeBox" key={l.locale}><div className="localeHead"><strong>{l.locale==='uk'?'🇺🇦 Українська':'🇷🇺 Русский'}</strong><label className="check"><input type="checkbox" checked={l.is_published!==false} onChange={e=>setForm({...form,locales:form.locales.map((x,j)=>j===i?{...x,is_published:e.target.checked}:x)})}/> Активна</label></div><Field label="Назва"><input value={l.title||''} onChange={e=>setForm({...form,locales:form.locales.map((x,j)=>j===i?{...x,title:e.target.value}:x)})}/></Field><Field label="Коротка назва"><input value={l.short_title||''} onChange={e=>setForm({...form,locales:form.locales.map((x,j)=>j===i?{...x,short_title:e.target.value}:x)})}/></Field><Field label="Опис"><textarea value={l.description||''} onChange={e=>setForm({...form,locales:form.locales.map((x,j)=>j===i?{...x,description:e.target.value}:x)})}/></Field><Field label="Вступ"><textarea className="tall" value={l.intro_text||''} onChange={e=>setForm({...form,locales:form.locales.map((x,j)=>j===i?{...x,intro_text:e.target.value}:x)})}/></Field></div>)}</div>
      </div>
      <div>
        <div className="adminCard"><div className="sectionHead"><div><h2>Кроки ({data.steps.length})</h2></div><button className="secondary" onClick={addStep}>+ Додати</button></div><div className="adminList">{data.steps.map(s=><Link className="adminListItem" key={s.step_number} href={`/admin/course/${slug}/step/${s.step_number}`}><div><strong>{s.step_number}. {s.title}</strong><small>{(s.course_step_locales||[]).map(l=>l.locale.toUpperCase()).join(' · ')||'UK'}</small></div><span>Редагувати →</span></Link>)}</div></div>
        <div className="adminCard"><h2>Де показувати курс</h2>{assign.map((a,i)=><div className="spaceAssign" key={a.space_slug}><label className="check"><input type="checkbox" checked={a.is_visible} onChange={e=>setAssign(assign.map((x,j)=>j===i?{...x,is_visible:e.target.checked}:x))}/><strong>{a.title}</strong> <code>{a.space_slug}</code></label>{a.is_visible&&<><Field label="Ціна у цьому просторі (порожньо = базова)"><input type="number" value={a.price_override_stars} onChange={e=>setAssign(assign.map((x,j)=>j===i?{...x,price_override_stars:e.target.value}:x))}/></Field><Field label="Доступ"><select value={a.access_override} onChange={e=>setAssign(assign.map((x,j)=>j===i?{...x,access_override:e.target.value}:x))}><option value="">Наслідувати курс</option><option value="free">Безкоштовно тут</option><option value="paid">Платно тут</option></select></Field></>}</div>)}</div>
        <div className="adminCard"><h2>Історія версій</h2><p className="hint">Кожне збереження курсу/кроку створює snapshot. Перед відновленням система автоматично робить ще один backup.</p><div className="adminList compactList">{(data.versions||[]).map(v=><div className="adminListItem" key={v.id}><div><strong>{v.version_label}</strong><small>{new Date(v.created_at).toLocaleString('uk-UA')} · {v.status}</small></div>{(v.version_label.startsWith('edit-')||v.version_label.startsWith('before-restore-'))?<button className="secondary" onClick={async()=>{if(confirm('Відновити цю версію? Поточний стан буде автоматично збережено.')){setBusy(true);try{await apiFetch(`/api/admin/courses/${slug}/versions/${v.id}/restore`,{method:'POST'});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}}>Відновити</button>:<span className="pill">IMPORT</span>}</div>)}</div></div>
      </div>
    </div>
  </main>
}
